version: "2"
x-redash-service: &redash-service
  image: redash/redash:10.1.0.b50633
  depends_on:
    - postgres
    - redis
  env_file: .env
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5001:5000"
      - "5678:5678"
    environment:
      REDASH_WEB_WORKERS: 1
  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 1
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
  postgres:
    image: postgres:latest
    env_file: .env
    environment:
      - PGDATA=/var/lib/postgresql/data/redashdb
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - "8080:5001"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
